spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: auth-service

mybatis:
  type-aliases-package: com.product.entity

server:
  port: 8051

logging:
  level:
    org:
      springframework:
        security: DEBUG

