spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 1234
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: auth-service
  redis:
    host: localhost
    password:
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
server:
  port: 8052

logging:
  level:
    org:
      springframework:
        security: DEBUG

