spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 930812
  cache:
    ehcache:
      config: classpath:ehcache.xml
  application:
    name: productService

mybatis:
  type-aliases-package: com.product.entity

server:
  port: 8001

logging:
  level:
    com:
      product: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8003/eureka}
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
